name: flutter_application_1
description: "Job Fair Offline Registration App â€” FairTrack"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.0
  image_picker: ^1.1.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  uuid: ^4.3.3
  intl: ^0.19.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  google_mlkit_text_recognition: ^0.15.1
  google_mlkit_entity_extraction: ^0.15.3
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
